name: Keep Replit Alive
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  ping: 
    runs-on: ubuntu-latest
    steps:
      - run: curl -sL --insecure "https://9f284a30-7914-4ee0-ac2e-1e1c8e39d9bd-00-3lkgwhuggd8m3.pike.replit.dev"/
      
 
